session_name: cihai
start_directory: ./ # load session relative to config location (project root).
before_script: ./.tmuxp-before-script.sh
windows:
- window_name: cihai
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 67%
  panes:
  - focus: true
  - pane
  - make watch_mypy
  - make start
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 67%
  start_directory: docs/
  panes:
  - focus: true
  - pane
  - pane
  - make start
