session_name: cihai
shell_command_before:
  - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
  - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
  - '[ ! -d .env/build ] || rm -rf .env/build'
windows:
- layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  panes:
  - shell_command:
    - vim
    - :Ex
    focus: true
  - shell_command:
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.py" 'python setup.py test'
  - pane
  - shell_command:
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env3 -a -f .env/bin/activate ] && source .env3/bin/activate || virtualenv .env --python=/usr/bin/python3.3'
    - '[ ! -d .env3/build ] || rm -rf .env3/build'
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.py" 'python setup.py test'
  start_directory: /home/tony/workspace/libunihan
  window_name: cihai
- layout: f4a0,145x50,0,0[145x33,0,0,220,145x16,0,34{48x16,0,34,221,47x16,49,34,222,48x16,97,34,223}]
  options:
    main-pane-height: 35
  panes:
  - pane
  - pane
  - pane
  - pane
  start_directory: /home/tony/workspace/libunihan/doc
  window_name: docs
