session_name: cihai
shell_command_before:
  - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
  - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
  - '[ ! -d .env/build ] || rm -rf .env/build'
windows:
- layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  panes:
  - shell_command:
    - vim
    - :Ex
    focus: true
  - shell_command:
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.py" 'python setup.py test'
  - pane
  - shell_command:
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env3 -a -f .env/bin/activate ] && source .env3/bin/activate || virtualenv .env --python=/usr/bin/python3.3'
    - '[ ! -d .env3/build ] || rm -rf .env3/build'
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.py" 'python setup.py test'
  window_name: cihai
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before: 
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
    - '[ ! -d .env/build ] || rm -rf .env/build'
    - command -v .env/bin/tmuxp >/dev/null 2>&1 || { pip install -e .; }
    - cd ./doc
  panes:
  - shell_command:
    - reset
    - vim
    - :Ex
    focus: true
  - pwd
  - echo 'docs built to <http://0.0.0.0:8008/_build/html>'; python -m SimpleHTTPServer 8008
  - shell_command:
    - command -v sphinx-quickstart >/dev/null 2>&1 || { pip install -r requirements.pip; }
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.rst" 'make html'
